name: Build NodeJs application
on: push  # when ever there is a commit in the repo than run the workflow 
jobs:
  job_build:  # this is name of the job 
    runs-on: ubuntu-latest  # this is the VM where the job will run
    steps: 
     - name: Checkout the code on runner VM 1.
       uses: actions/checkout@v7  
       # this action will checkout the code on the runner VM
     - name: Install NodeJS 
       uses: actions/setup-node@v7
       with: 
        node-version: '18'  # this will install nodejs version 18 on the runner VM
     - name: Install nodejs dependencies 
       run: npm ci  
       # this will install all the dependencies mentioned in package.json file
     - name: Execute test cases 
       run: npm test  
       # this will execute all the test cases mentioned in the src folder
     - name: Build the application 
       run: npm run build  
       # this will build the application and create a dist folder
     - name: Upload the build from runner to the github repo 
       uses: actions/upload-artifact@v7
       with: 
        name: buildfile  # this is the name of the artifact which will be created in the github repo
        path: dist
