name: Matrix strategy workflow
on: push
jobs:
  nodejs_matrix:
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18, 14, 16, 12]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout the code on runner VM
        uses: actions/checkout@v7
      - name: Install NodeJS 
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install nodejs dependencies 
        run: npm ci  
      - name: Execute test cases 
        run: npm test
